### PR TITLE
Upgrade firebase web library to version 2.3.1

### PR DESCRIPTION
**Pull request by albertolobrano**
Fixed issue 90

### CODE REVIEW

**Comment by albertolobrano** [comment]
@addyosmani do you know why this is failing ?

**Comment by albertolobrano** [comment]
I am wondering if this is failing due to the change i made or something else. Can someone help me figure it out?  It is complaining that it does not find firefox .

**Comment by addyosmani** [comment]
Afaik, the travis setup has been pretty flakey on GWC and it may well not be your changes.

**Comment by addyosmani** [comment]
Did you test that the element and https://github.com/GoogleWebComponents/firebase-element/tree/master/test were all working post update?

**Comment by albertolobrano** [comment]
yes.  I am using the component with the last library and everything is working fine

**Comment by addyosmani** [comment]
:ok_hand: :ok: That's great. Verifying locally.

**Comment by addyosmani** [comment]
Tested locally and everything looks good on this end. Closed via https://github.com/GoogleWebComponents/firebase-element/commit/3ded0c50b59df7e61ad0206ad3a26c07588ef4e9

**Pull request closed without merging**
