### PR TITLE
Missing ignore

### PR DESCRIPTION
**Pull request by MeTaNoV**
Corrects it!

[Review on Reviewable](https://reviewable.io/reviews/googlewebcomponents/firebase-element/87)

### CODE REVIEW

**Comment by MeTaNoV** [comment]
@rictic `firebase-element` are not included in Tedium process?

**Comment by ebidel** [comment]
LGTM

**Comment by rictic** [comment]
@metanov Oh, good question. Currently tedium is only running over the PolymerElements org.

@ebidel @addyosmani @robdodson @cdata

What do you all think about running tedium over the GoogleWebComponents org's elements? Currently tedium will:

* automatically generate the README.md file based on the docs for each element it finds in the repo
* do a bunch of transformations to your travis.yml file to keep it working well with sauce, running polylint, etc
* ensure that any tests are run both with and without `?dom=shadow`
* copy over https://github.com/PolymerElements/ContributionGuide/blob/master/CONTRIBUTING.md and keep it up to date
* a number of minor normalization steps to `bower.json` files
* no doubt more stuff in the future

We can also blacklist individual repos from specific cleanup passes or from tedium touching them at all.

**Comment by ebidel** [comment]
+1. We'll probably have some failing tests but we should hook it up.

**Comment by robdodson** [comment]
sgtm!

**Pull request merged**
