### PR TITLE
Set __firebaseKey__ for local additions. Fixes #61

### LINKED ISSUE #61: firebase-collection: Modifying new locally-pushed items throws
Repro: http://jsbin.com/paqaro/edit?html,console,output

* Click 'Add'
* Type in input
* Note error

```
Uncaught Error: Firebase.child failed: First argument was an invalid path: "undefined". Paths must be non-empty strings and can't contain ".", "#", "$", "[", or "]"
```

This is due to the previous https://github.com/GoogleWebComponents/firebase-element/pull/60 fix which avoided the round-trip modification from the server, which is where the local `__firebaseKey__` property is set.  Simple fix is to set the new key in `add` after `push`, as its synchronously available there.

### PR DESCRIPTION
**Pull request by kevinpschaaf**

### CODE REVIEW

**Comment by kevinpschaaf** [comment]
Resolves repro in jsBin: http://jsbin.com/hayazi/edit?html,console,output

Still need to add unit tests.

**Comment by ebidel** [comment]
LGTM. Do you want to add tests now or in a different PR?

**Comment by kevinpschaaf** [comment]
Just added tests, but in the process I hit an issue I need to review with @cdata: Looks like the previous change to https://github.com/GoogleWebComponents/firebase-element/pull/60 broke primitive array support, since it was in the remote data handling that primitive values were wrapped (which no longer happens).  So this fix only works for arrays with object-valued items; the solution for primitive wasn't immediately clear, would be good to discuss.

**Comment by cdata** [comment]
@kevinpschaaf @robdodson I am gonna close this PR since #63 supersedes it.

**Pull request closed without merging**
